// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Data;

#nullable disable

namespace Shop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129235517_addedProductAndCategoryAndSeededData")]
    partial class addedProductAndCategoryAndSeededData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Shop.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("4b36427b-06c9-f038-cb04-0f87b57cd4b6"),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("db87dc8d-6282-b96d-6d20-6135fd199215"),
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = new Guid("b9f4c1c2-4602-2ee4-0c21-a90061bf1a9e"),
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("486d4f30-e0f9-91c8-5ce6-d7bbcdea7c72"),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("1ec213ba-958b-ada3-7541-c3b90b604696"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("3da842e9-e1c9-282b-a65f-0c733e362c8e"),
                            Name = "Outdoors"
                        },
                        new
                        {
                            Id = new Guid("45dc0705-b9a4-9ac9-839e-04d851859024"),
                            Name = "Tools"
                        },
                        new
                        {
                            Id = new Guid("f2ca3a01-32f0-f696-e535-9639370a972a"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("55ba3f5b-8844-a2de-4542-264f55d97b4e"),
                            Name = "Health"
                        });
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fc4f135-d414-4e46-be84-32614c946dad"),
                            CategoryId = new Guid("3da842e9-e1c9-282b-a65f-0c733e362c8e"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 75.37m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1064",
                            IsAvailable = false,
                            Name = "Licensed Soft Salad",
                            NetAmount = 62.81m,
                            SKU = "0360669820501",
                            Tag = "Rustic",
                            TaxAmount = 12.56m
                        },
                        new
                        {
                            Id = new Guid("746a469a-8506-ab04-41f9-aeb9a1ddaf2b"),
                            CategoryId = new Guid("55ba3f5b-8844-a2de-4542-264f55d97b4e"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            GrossAmount = 959.93m,
                            ImageUrl = "https://picsum.photos/640/480/?image=511",
                            IsAvailable = true,
                            Name = "Refined Wooden Pizza",
                            NetAmount = 799.94m,
                            SKU = "5446087306966",
                            Tag = "Rustic",
                            TaxAmount = 159.99m
                        },
                        new
                        {
                            Id = new Guid("ad36d7f5-0f3f-41b1-b505-b3adef06fe5c"),
                            CategoryId = new Guid("55ba3f5b-8844-a2de-4542-264f55d97b4e"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 890.51m,
                            ImageUrl = "https://picsum.photos/640/480/?image=624",
                            IsAvailable = true,
                            Name = "Generic Wooden Cheese",
                            NetAmount = 742.09m,
                            SKU = "9936432295893",
                            Tag = "Rustic",
                            TaxAmount = 148.42m
                        },
                        new
                        {
                            Id = new Guid("b8df9891-21a3-7aa1-7b27-6f226360b931"),
                            CategoryId = new Guid("45dc0705-b9a4-9ac9-839e-04d851859024"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 241.33m,
                            ImageUrl = "https://picsum.photos/640/480/?image=241",
                            IsAvailable = false,
                            Name = "Intelligent Steel Table",
                            NetAmount = 201.11m,
                            SKU = "3334132477179",
                            Tag = "Fantastic",
                            TaxAmount = 40.22m
                        },
                        new
                        {
                            Id = new Guid("bc7be224-61dc-5b6c-b68b-92a0cdc3e596"),
                            CategoryId = new Guid("1ec213ba-958b-ada3-7541-c3b90b604696"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 822.37m,
                            ImageUrl = "https://picsum.photos/640/480/?image=567",
                            IsAvailable = true,
                            Name = "Licensed Rubber Hat",
                            NetAmount = 685.31m,
                            SKU = "3899911894030",
                            Tag = "Gorgeous",
                            TaxAmount = 137.06m
                        },
                        new
                        {
                            Id = new Guid("3e6f02bc-21e8-2fc8-0be6-1ec580cdb714"),
                            CategoryId = new Guid("1ec213ba-958b-ada3-7541-c3b90b604696"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 849.72m,
                            ImageUrl = "https://picsum.photos/640/480/?image=146",
                            IsAvailable = true,
                            Name = "Ergonomic Fresh Soap",
                            NetAmount = 708.1m,
                            SKU = "8943450670954",
                            Tag = "Handmade",
                            TaxAmount = 141.62m
                        },
                        new
                        {
                            Id = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CategoryId = new Guid("db87dc8d-6282-b96d-6d20-6135fd199215"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 722.63m,
                            ImageUrl = "https://picsum.photos/640/480/?image=342",
                            IsAvailable = true,
                            Name = "Practical Rubber Bike",
                            NetAmount = 602.19m,
                            SKU = "4445048152865",
                            Tag = "Awesome",
                            TaxAmount = 120.44m
                        },
                        new
                        {
                            Id = new Guid("34dbed0b-384d-922b-af8f-2135437dfa28"),
                            CategoryId = new Guid("f2ca3a01-32f0-f696-e535-9639370a972a"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 684.00m,
                            ImageUrl = "https://picsum.photos/640/480/?image=51",
                            IsAvailable = true,
                            Name = "Gorgeous Steel Sausages",
                            NetAmount = 570.0m,
                            SKU = "8231041512258",
                            Tag = "Handcrafted",
                            TaxAmount = 114.00m
                        },
                        new
                        {
                            Id = new Guid("ba1759b9-d651-0c99-48fa-e0cc85e51afa"),
                            CategoryId = new Guid("3da842e9-e1c9-282b-a65f-0c733e362c8e"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 743.84m,
                            ImageUrl = "https://picsum.photos/640/480/?image=68",
                            IsAvailable = true,
                            Name = "Licensed Frozen Fish",
                            NetAmount = 619.87m,
                            SKU = "7388607631654",
                            Tag = "Generic",
                            TaxAmount = 123.97m
                        },
                        new
                        {
                            Id = new Guid("6d2a8812-1bb0-7943-4477-549867006bd5"),
                            CategoryId = new Guid("55ba3f5b-8844-a2de-4542-264f55d97b4e"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 41.06m,
                            ImageUrl = "https://picsum.photos/640/480/?image=417",
                            IsAvailable = true,
                            Name = "Unbranded Rubber Gloves",
                            NetAmount = 34.22m,
                            SKU = "6621078653444",
                            Tag = "Handcrafted",
                            TaxAmount = 6.84m
                        },
                        new
                        {
                            Id = new Guid("cdb56e7a-d565-201c-4357-80bfc83e11d0"),
                            CategoryId = new Guid("3da842e9-e1c9-282b-a65f-0c733e362c8e"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 999.38m,
                            ImageUrl = "https://picsum.photos/640/480/?image=728",
                            IsAvailable = true,
                            Name = "Unbranded Steel Ball",
                            NetAmount = 832.82m,
                            SKU = "1732558543829",
                            Tag = "Gorgeous",
                            TaxAmount = 166.56m
                        },
                        new
                        {
                            Id = new Guid("a0cbd37a-7940-45f5-0e79-64655bc4a32d"),
                            CategoryId = new Guid("4b36427b-06c9-f038-cb04-0f87b57cd4b6"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 160.75m,
                            ImageUrl = "https://picsum.photos/640/480/?image=609",
                            IsAvailable = false,
                            Name = "Sleek Concrete Pants",
                            NetAmount = 133.96m,
                            SKU = "0016545660876",
                            Tag = "Unbranded",
                            TaxAmount = 26.79m
                        },
                        new
                        {
                            Id = new Guid("6c36892a-650e-3cbc-9acc-091032efe1a4"),
                            CategoryId = new Guid("b9f4c1c2-4602-2ee4-0c21-a90061bf1a9e"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 57.80m,
                            ImageUrl = "https://picsum.photos/640/480/?image=187",
                            IsAvailable = true,
                            Name = "Gorgeous Rubber Bacon",
                            NetAmount = 48.17m,
                            SKU = "4676739810843",
                            Tag = "Generic",
                            TaxAmount = 9.63m
                        },
                        new
                        {
                            Id = new Guid("71f3529f-82f6-6b2b-93ed-88f02a00cc6a"),
                            CategoryId = new Guid("486d4f30-e0f9-91c8-5ce6-d7bbcdea7c72"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 820.08m,
                            ImageUrl = "https://picsum.photos/640/480/?image=892",
                            IsAvailable = true,
                            Name = "Sleek Granite Car",
                            NetAmount = 683.4m,
                            SKU = "0286987635187",
                            Tag = "Small",
                            TaxAmount = 136.68m
                        },
                        new
                        {
                            Id = new Guid("1b01a032-bf97-0e38-b76a-e1f0ced07786"),
                            CategoryId = new Guid("b9f4c1c2-4602-2ee4-0c21-a90061bf1a9e"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 569.30m,
                            ImageUrl = "https://picsum.photos/640/480/?image=398",
                            IsAvailable = true,
                            Name = "Generic Wooden Salad",
                            NetAmount = 474.42m,
                            SKU = "8499343245513",
                            Tag = "Generic",
                            TaxAmount = 94.88m
                        },
                        new
                        {
                            Id = new Guid("af5a9b26-5dc0-d53d-1e03-d7343b0cb15c"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 753.13m,
                            ImageUrl = "https://picsum.photos/640/480/?image=919",
                            IsAvailable = true,
                            Name = "Rustic Frozen Bacon",
                            NetAmount = 627.61m,
                            SKU = "9334829225223",
                            Tag = "Handmade",
                            TaxAmount = 125.52m
                        },
                        new
                        {
                            Id = new Guid("11ff64b9-fdf4-1396-0c8b-8e67c138318e"),
                            CategoryId = new Guid("f2ca3a01-32f0-f696-e535-9639370a972a"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 631.78m,
                            ImageUrl = "https://picsum.photos/640/480/?image=863",
                            IsAvailable = true,
                            Name = "Generic Frozen Bacon",
                            NetAmount = 526.48m,
                            SKU = "9075701227705",
                            Tag = "Unbranded",
                            TaxAmount = 105.30m
                        },
                        new
                        {
                            Id = new Guid("66014240-eac0-8ebc-e901-6a60dcec73fc"),
                            CategoryId = new Guid("b9f4c1c2-4602-2ee4-0c21-a90061bf1a9e"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 883.88m,
                            ImageUrl = "https://picsum.photos/640/480/?image=188",
                            IsAvailable = true,
                            Name = "Licensed Frozen Computer",
                            NetAmount = 736.57m,
                            SKU = "5255768134114",
                            Tag = "Gorgeous",
                            TaxAmount = 147.31m
                        },
                        new
                        {
                            Id = new Guid("bbcec637-02b0-1010-108e-3fe6ecc58d5a"),
                            CategoryId = new Guid("3da842e9-e1c9-282b-a65f-0c733e362c8e"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 3.89m,
                            ImageUrl = "https://picsum.photos/640/480/?image=912",
                            IsAvailable = true,
                            Name = "Practical Metal Bacon",
                            NetAmount = 3.24m,
                            SKU = "1603134376585",
                            Tag = "Ergonomic",
                            TaxAmount = 0.65m
                        },
                        new
                        {
                            Id = new Guid("d2220f2f-1472-a119-4ab9-b50283d1a3c1"),
                            CategoryId = new Guid("f2ca3a01-32f0-f696-e535-9639370a972a"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 598.82m,
                            ImageUrl = "https://picsum.photos/640/480/?image=356",
                            IsAvailable = false,
                            Name = "Ergonomic Metal Ball",
                            NetAmount = 499.02m,
                            SKU = "5252267198791",
                            Tag = "Intelligent",
                            TaxAmount = 99.80m
                        },
                        new
                        {
                            Id = new Guid("ff2c0c8d-4067-b830-6f0a-03804e7c30f9"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 135.18m,
                            ImageUrl = "https://picsum.photos/640/480/?image=693",
                            IsAvailable = true,
                            Name = "Sleek Plastic Chair",
                            NetAmount = 112.65m,
                            SKU = "2656616840851",
                            Tag = "Incredible",
                            TaxAmount = 22.53m
                        },
                        new
                        {
                            Id = new Guid("97ef5daf-2fdb-3978-eae1-21e4dd82ba8b"),
                            CategoryId = new Guid("4b36427b-06c9-f038-cb04-0f87b57cd4b6"),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 283.35m,
                            ImageUrl = "https://picsum.photos/640/480/?image=820",
                            IsAvailable = true,
                            Name = "Tasty Wooden Shirt",
                            NetAmount = 236.12m,
                            SKU = "7510879304466",
                            Tag = "Licensed",
                            TaxAmount = 47.23m
                        },
                        new
                        {
                            Id = new Guid("7704b3b1-c39f-8a90-c001-cfa1badf60e2"),
                            CategoryId = new Guid("db87dc8d-6282-b96d-6d20-6135fd199215"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 344.09m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1020",
                            IsAvailable = true,
                            Name = "Generic Granite Mouse",
                            NetAmount = 286.74m,
                            SKU = "4932095970097",
                            Tag = "Handmade",
                            TaxAmount = 57.35m
                        },
                        new
                        {
                            Id = new Guid("658db4a5-cb0a-4dd8-0d01-04245d18b820"),
                            CategoryId = new Guid("45dc0705-b9a4-9ac9-839e-04d851859024"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 818.25m,
                            ImageUrl = "https://picsum.photos/640/480/?image=400",
                            IsAvailable = true,
                            Name = "Incredible Concrete Pizza",
                            NetAmount = 681.88m,
                            SKU = "1159749098010",
                            Tag = "Practical",
                            TaxAmount = 136.37m
                        },
                        new
                        {
                            Id = new Guid("293f5001-bbc4-027a-3885-35f5e102c866"),
                            CategoryId = new Guid("4b36427b-06c9-f038-cb04-0f87b57cd4b6"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 203.40m,
                            ImageUrl = "https://picsum.photos/640/480/?image=294",
                            IsAvailable = true,
                            Name = "Generic Steel Soap",
                            NetAmount = 169.5m,
                            SKU = "0648518648354",
                            Tag = "Small",
                            TaxAmount = 33.90m
                        },
                        new
                        {
                            Id = new Guid("a8f32d88-faba-3c22-5eea-f5756ba728e1"),
                            CategoryId = new Guid("b9f4c1c2-4602-2ee4-0c21-a90061bf1a9e"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            GrossAmount = 415.15m,
                            ImageUrl = "https://picsum.photos/640/480/?image=276",
                            IsAvailable = true,
                            Name = "Fantastic Wooden Car",
                            NetAmount = 345.96m,
                            SKU = "2105648250072",
                            Tag = "Gorgeous",
                            TaxAmount = 69.19m
                        },
                        new
                        {
                            Id = new Guid("3f3716e9-251c-2195-4dc6-d2a85ec450d7"),
                            CategoryId = new Guid("b9f4c1c2-4602-2ee4-0c21-a90061bf1a9e"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 233.35m,
                            ImageUrl = "https://picsum.photos/640/480/?image=579",
                            IsAvailable = true,
                            Name = "Licensed Frozen Pizza",
                            NetAmount = 194.46m,
                            SKU = "2651437507358",
                            Tag = "Sleek",
                            TaxAmount = 38.89m
                        },
                        new
                        {
                            Id = new Guid("ad7fc9ad-6982-ed0a-0c96-3a4183ed8096"),
                            CategoryId = new Guid("db87dc8d-6282-b96d-6d20-6135fd199215"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 527.76m,
                            ImageUrl = "https://picsum.photos/640/480/?image=570",
                            IsAvailable = true,
                            Name = "Tasty Metal Towels",
                            NetAmount = 439.8m,
                            SKU = "5250898485808",
                            Tag = "Sleek",
                            TaxAmount = 87.96m
                        },
                        new
                        {
                            Id = new Guid("de86cb3c-614e-25b1-1716-23e995a6294f"),
                            CategoryId = new Guid("f2ca3a01-32f0-f696-e535-9639370a972a"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 401.13m,
                            ImageUrl = "https://picsum.photos/640/480/?image=110",
                            IsAvailable = true,
                            Name = "Tasty Wooden Chicken",
                            NetAmount = 334.28m,
                            SKU = "3761355657222",
                            Tag = "Tasty",
                            TaxAmount = 66.85m
                        },
                        new
                        {
                            Id = new Guid("236fad4e-25a0-1871-720f-0f562caaa5ed"),
                            CategoryId = new Guid("55ba3f5b-8844-a2de-4542-264f55d97b4e"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 817.24m,
                            ImageUrl = "https://picsum.photos/640/480/?image=959",
                            IsAvailable = true,
                            Name = "Ergonomic Granite Chips",
                            NetAmount = 681.03m,
                            SKU = "5317155095306",
                            Tag = "Intelligent",
                            TaxAmount = 136.21m
                        },
                        new
                        {
                            Id = new Guid("894b19d0-3c14-4737-c090-309e36088843"),
                            CategoryId = new Guid("f2ca3a01-32f0-f696-e535-9639370a972a"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 956.80m,
                            ImageUrl = "https://picsum.photos/640/480/?image=389",
                            IsAvailable = true,
                            Name = "Fantastic Cotton Tuna",
                            NetAmount = 797.33m,
                            SKU = "2549571886494",
                            Tag = "Fantastic",
                            TaxAmount = 159.47m
                        },
                        new
                        {
                            Id = new Guid("cff34447-dac4-0bd6-34c9-17da5328c54e"),
                            CategoryId = new Guid("55ba3f5b-8844-a2de-4542-264f55d97b4e"),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 728.95m,
                            ImageUrl = "https://picsum.photos/640/480/?image=702",
                            IsAvailable = true,
                            Name = "Small Cotton Car",
                            NetAmount = 607.46m,
                            SKU = "1575584903133",
                            Tag = "Handmade",
                            TaxAmount = 121.49m
                        },
                        new
                        {
                            Id = new Guid("62afa0d8-69de-3b4f-d125-ec89ee717aaa"),
                            CategoryId = new Guid("f2ca3a01-32f0-f696-e535-9639370a972a"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 721.85m,
                            ImageUrl = "https://picsum.photos/640/480/?image=169",
                            IsAvailable = false,
                            Name = "Intelligent Plastic Shirt",
                            NetAmount = 601.54m,
                            SKU = "2116260793298",
                            Tag = "Small",
                            TaxAmount = 120.31m
                        },
                        new
                        {
                            Id = new Guid("ab80837d-b8ad-bda9-b804-74396c45a374"),
                            CategoryId = new Guid("1ec213ba-958b-ada3-7541-c3b90b604696"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            GrossAmount = 417.72m,
                            ImageUrl = "https://picsum.photos/640/480/?image=124",
                            IsAvailable = true,
                            Name = "Sleek Soft Chair",
                            NetAmount = 348.1m,
                            SKU = "7961184618722",
                            Tag = "Small",
                            TaxAmount = 69.62m
                        },
                        new
                        {
                            Id = new Guid("4c8b5c9d-dc71-da13-da94-9eede26702d9"),
                            CategoryId = new Guid("f2ca3a01-32f0-f696-e535-9639370a972a"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            GrossAmount = 127.66m,
                            ImageUrl = "https://picsum.photos/640/480/?image=132",
                            IsAvailable = true,
                            Name = "Gorgeous Fresh Keyboard",
                            NetAmount = 106.38m,
                            SKU = "2782201720526",
                            Tag = "Gorgeous",
                            TaxAmount = 21.28m
                        },
                        new
                        {
                            Id = new Guid("b2f10e5e-5f40-4ea7-a6b3-30c82a57fa83"),
                            CategoryId = new Guid("1ec213ba-958b-ada3-7541-c3b90b604696"),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            GrossAmount = 609.57m,
                            ImageUrl = "https://picsum.photos/640/480/?image=219",
                            IsAvailable = false,
                            Name = "Licensed Soft Soap",
                            NetAmount = 507.98m,
                            SKU = "2841324405793",
                            Tag = "Intelligent",
                            TaxAmount = 101.59m
                        },
                        new
                        {
                            Id = new Guid("cb11250a-6e7c-f074-7045-cf5e8e2823c0"),
                            CategoryId = new Guid("1ec213ba-958b-ada3-7541-c3b90b604696"),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 718.84m,
                            ImageUrl = "https://picsum.photos/640/480/?image=237",
                            IsAvailable = true,
                            Name = "Ergonomic Frozen Salad",
                            NetAmount = 599.03m,
                            SKU = "4231303663739",
                            Tag = "Handcrafted",
                            TaxAmount = 119.81m
                        },
                        new
                        {
                            Id = new Guid("d4c8431f-69cb-e524-dcfd-be25b9648737"),
                            CategoryId = new Guid("4b36427b-06c9-f038-cb04-0f87b57cd4b6"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 870.70m,
                            ImageUrl = "https://picsum.photos/640/480/?image=220",
                            IsAvailable = false,
                            Name = "Handmade Concrete Ball",
                            NetAmount = 725.58m,
                            SKU = "9699099231610",
                            Tag = "Fantastic",
                            TaxAmount = 145.12m
                        },
                        new
                        {
                            Id = new Guid("b16f6bf0-8fc6-01c4-45fc-25d1c2ae3ca1"),
                            CategoryId = new Guid("db87dc8d-6282-b96d-6d20-6135fd199215"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 606.42m,
                            ImageUrl = "https://picsum.photos/640/480/?image=649",
                            IsAvailable = false,
                            Name = "Handmade Fresh Keyboard",
                            NetAmount = 505.35m,
                            SKU = "5661939151482",
                            Tag = "Small",
                            TaxAmount = 101.07m
                        },
                        new
                        {
                            Id = new Guid("f5cf9f9d-c4ad-c23d-1a13-be8db2d1effa"),
                            CategoryId = new Guid("1ec213ba-958b-ada3-7541-c3b90b604696"),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 441.21m,
                            ImageUrl = "https://picsum.photos/640/480/?image=215",
                            IsAvailable = true,
                            Name = "Licensed Granite Bike",
                            NetAmount = 367.68m,
                            SKU = "1003210765737",
                            Tag = "Sleek",
                            TaxAmount = 73.53m
                        },
                        new
                        {
                            Id = new Guid("53056b94-1dbf-b1fa-a5b7-8125ae06942c"),
                            CategoryId = new Guid("db87dc8d-6282-b96d-6d20-6135fd199215"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 495.37m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1031",
                            IsAvailable = true,
                            Name = "Unbranded Wooden Table",
                            NetAmount = 412.81m,
                            SKU = "9328865264278",
                            Tag = "Licensed",
                            TaxAmount = 82.56m
                        },
                        new
                        {
                            Id = new Guid("bc5b2d86-eb6d-71df-c1cc-47542edc083f"),
                            CategoryId = new Guid("45dc0705-b9a4-9ac9-839e-04d851859024"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 532.43m,
                            ImageUrl = "https://picsum.photos/640/480/?image=308",
                            IsAvailable = true,
                            Name = "Sleek Wooden Car",
                            NetAmount = 443.69m,
                            SKU = "8103121513359",
                            Tag = "Unbranded",
                            TaxAmount = 88.74m
                        },
                        new
                        {
                            Id = new Guid("3778422b-9360-8479-d534-91cb2da9cab7"),
                            CategoryId = new Guid("4b36427b-06c9-f038-cb04-0f87b57cd4b6"),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 583.92m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1062",
                            IsAvailable = false,
                            Name = "Unbranded Wooden Ball",
                            NetAmount = 486.6m,
                            SKU = "8516700426429",
                            Tag = "Sleek",
                            TaxAmount = 97.32m
                        },
                        new
                        {
                            Id = new Guid("ff6ad31d-facc-a519-18e7-a3da67372034"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 623.85m,
                            ImageUrl = "https://picsum.photos/640/480/?image=49",
                            IsAvailable = true,
                            Name = "Ergonomic Wooden Shoes",
                            NetAmount = 519.88m,
                            SKU = "0263455247615",
                            Tag = "Practical",
                            TaxAmount = 103.97m
                        },
                        new
                        {
                            Id = new Guid("06f13db4-e20d-d175-4dc0-6102eb6ab8c3"),
                            CategoryId = new Guid("55ba3f5b-8844-a2de-4542-264f55d97b4e"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 773.34m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1047",
                            IsAvailable = false,
                            Name = "Sleek Fresh Tuna",
                            NetAmount = 644.45m,
                            SKU = "3713380303759",
                            Tag = "Practical",
                            TaxAmount = 128.89m
                        },
                        new
                        {
                            Id = new Guid("8d5ab71c-034e-da9a-1086-01fde3f20e86"),
                            CategoryId = new Guid("4b36427b-06c9-f038-cb04-0f87b57cd4b6"),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 504.63m,
                            ImageUrl = "https://picsum.photos/640/480/?image=603",
                            IsAvailable = false,
                            Name = "Ergonomic Plastic Computer",
                            NetAmount = 420.52m,
                            SKU = "3148886038346",
                            Tag = "Awesome",
                            TaxAmount = 84.11m
                        },
                        new
                        {
                            Id = new Guid("d6aafc42-f6e3-acae-3318-1b594abf423a"),
                            CategoryId = new Guid("3da842e9-e1c9-282b-a65f-0c733e362c8e"),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 841.31m,
                            ImageUrl = "https://picsum.photos/640/480/?image=339",
                            IsAvailable = true,
                            Name = "Ergonomic Soft Bike",
                            NetAmount = 701.09m,
                            SKU = "5677535055604",
                            Tag = "Tasty",
                            TaxAmount = 140.22m
                        },
                        new
                        {
                            Id = new Guid("2b094ff5-1088-24bb-0045-3a92ee845aa0"),
                            CategoryId = new Guid("db87dc8d-6282-b96d-6d20-6135fd199215"),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 934.18m,
                            ImageUrl = "https://picsum.photos/640/480/?image=433",
                            IsAvailable = true,
                            Name = "Small Granite Computer",
                            NetAmount = 778.48m,
                            SKU = "6834346173203",
                            Tag = "Generic",
                            TaxAmount = 155.70m
                        },
                        new
                        {
                            Id = new Guid("bd379db1-419f-db03-1ee8-401393769f0b"),
                            CategoryId = new Guid("b9f4c1c2-4602-2ee4-0c21-a90061bf1a9e"),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            GrossAmount = 163.51m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1028",
                            IsAvailable = true,
                            Name = "Incredible Soft Pants",
                            NetAmount = 136.26m,
                            SKU = "7640711982658",
                            Tag = "Practical",
                            TaxAmount = 27.25m
                        },
                        new
                        {
                            Id = new Guid("965447c4-df04-2eeb-9753-0eabaf176a5e"),
                            CategoryId = new Guid("4b36427b-06c9-f038-cb04-0f87b57cd4b6"),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            GrossAmount = 952.97m,
                            ImageUrl = "https://picsum.photos/640/480/?image=489",
                            IsAvailable = true,
                            Name = "Licensed Rubber Gloves",
                            NetAmount = 794.14m,
                            SKU = "0960171323134",
                            Tag = "Small",
                            TaxAmount = 158.83m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.HasOne("Shop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
