// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Data;

#nullable disable

namespace Shop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214090701_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Shop.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("36427b23-c94b-3806-f0cb-040f87b57cd4"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 3, DateTimeKind.Local).AddTicks(1721),
                            ModifiedById = new Guid("dc8dd8b6-db87-6282-6db9-6d206135fd19"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 8, DateTimeKind.Local).AddTicks(7224),
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("30639e1a-6d4f-f948-e0c8-915ce6d7bbcd"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 10, DateTimeKind.Local).AddTicks(9612),
                            ModifiedById = new Guid("30727cea-13ba-1ec2-8b95-a3ad7541c3b9"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 10, DateTimeKind.Local).AddTicks(9682),
                            Name = "Movies"
                        },
                        new
                        {
                            Id = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("8e2c363e-0531-dc07-45a4-b9c99a839e04"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 10, DateTimeKind.Local).AddTicks(9959),
                            ModifiedById = new Guid("908551d8-3324-3a01-caf2-f03296f6e535"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 10, DateTimeKind.Local).AddTicks(9976),
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = new Guid("970a3739-d92a-3f5b-ba55-4488dea24542"),
                            CreatedById = new Guid("d9554f26-4e7b-350b-f1c4-3f14d4464ebe"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local),
                            ModifiedById = new Guid("4c613284-6d94-77ad-2a50-6adebcb2eb50"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(5),
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("41ab0485-aef9-a1b9-ddaf-2be42d783fd8"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(21),
                            ModifiedById = new Guid("d6e569ee-2ea7-1728-7520-bfc647dde4e5"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(25),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("85dcab8e-5e9d-dc57-94cb-d8eef259ffca"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(42),
                            ModifiedById = new Guid("4155ef45-9891-b8df-a321-a17a7b276f22"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(47),
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("a917aae2-d41a-ccf5-24e2-7bbcdc616c5b"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(66),
                            ModifiedById = new Guid("a0928bb6-c3cd-96e5-db62-c0ed9adf4f5e"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(71),
                            Name = "Games"
                        },
                        new
                        {
                            Id = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("2fc821e8-e60b-c51e-80cd-b71408314492"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(88),
                            ModifiedById = new Guid("c815c61c-03ef-413d-07dc-68e167ba1f5f"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(92),
                            Name = "Toys"
                        },
                        new
                        {
                            Id = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("edf6bfea-4fa7-e4e5-8628-2e7d3d5dc6ae"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(110),
                            ModifiedById = new Guid("7f59c357-0b86-dbed-344d-382b92af8f21"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(115),
                            Name = "Home"
                        },
                        new
                        {
                            Id = new Guid("28fa7d43-a972-cc5e-da01-06bd633d5911"),
                            CreatedById = new Guid("62b33afd-17b3-d1df-1ab9-5917ba51d699"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(131),
                            ModifiedById = new Guid("e0fa480c-85cc-1ae5-fab2-ab09e71ed010"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 11, DateTimeKind.Local).AddTicks(136),
                            Name = "Baby"
                        });
                });

            modelBuilder.Entity("Shop.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<Guid>("OrderHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Shop.Models.OrderHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderHeader");
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc75941a-81bf-9e2b-280e-b94f4712882a"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("431bb06d-4479-5477-9867-006bd5e9fce8"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 14, DateTimeKind.Local).AddTicks(9558),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            GrossAmount = 452.36m,
                            ImageUrl = "https://picsum.photos/640/480/?image=885",
                            IsAvailable = false,
                            ModifiedById = new Guid("bda03848-bc61-c64d-ce42-a3772ccbb3a0"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 15, DateTimeKind.Local).AddTicks(3217),
                            Name = "Handcrafted Frozen Chicken",
                            NetAmount = 376.97m,
                            SKU = "2674098486848",
                            Tag = "Ergonomic",
                            TaxAmount = 75.39m
                        },
                        new
                        {
                            Id = new Guid("62b0c9cb-7454-a136-0028-cdb46047f66f"),
                            CategoryId = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("d37a328e-a0cb-7940-f545-0e7964655bc4"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(50),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 758.42m,
                            ImageUrl = "https://picsum.photos/640/480/?image=495",
                            IsAvailable = true,
                            ModifiedById = new Guid("15582da3-0cca-5961-2e33-1cf875a32077"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(126),
                            Name = "Licensed Rubber Keyboard",
                            NetAmount = 632.02m,
                            SKU = "1991869257980",
                            Tag = "Handmade",
                            TaxAmount = 126.40m
                        },
                        new
                        {
                            Id = new Guid("d182a4e1-a421-8397-4703-522596a895e2"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("866838bd-8b2d-9f93-52f3-71f6822b6b93"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1161),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 835.39m,
                            ImageUrl = "https://picsum.photos/640/480/?image=902",
                            IsAvailable = true,
                            ModifiedById = new Guid("2af088ed-cc00-976a-0fa7-423319e8ce14"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1169),
                            Name = "Handmade Metal Gloves",
                            NetAmount = 696.16m,
                            SKU = "5188855047977",
                            Tag = "Sleek",
                            TaxAmount = 139.23m
                        },
                        new
                        {
                            Id = new Guid("cef0e16a-77d0-4986-6085-69245c4eca1c"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("c641eb9a-199a-4d1e-3b64-6ea5269b5aaf"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1288),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 18.51m,
                            ImageUrl = "https://picsum.photos/640/480/?image=797",
                            IsAvailable = true,
                            ModifiedById = new Guid("d53d5dc0-031e-34d7-3b0c-b15c1509d551"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1293),
                            Name = "Fantastic Cotton Shoes",
                            NetAmount = 15.42m,
                            SKU = "8292252287243",
                            Tag = "Unbranded",
                            TaxAmount = 3.09m
                        },
                        new
                        {
                            Id = new Guid("1396fdf4-8b0c-678e-c138-318e1c6d269d"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("3f78b887-12ec-717b-6b2b-5ae8ec315ba5"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1381),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 174.88m,
                            ImageUrl = "https://picsum.photos/640/480/?image=134",
                            IsAvailable = true,
                            ModifiedById = new Guid("014240d5-c066-bcea-8ee9-016a60dcec73"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1386),
                            Name = "Generic Soft Sausages",
                            NetAmount = 145.73m,
                            SKU = "1525576813414",
                            Tag = "Gorgeous",
                            TaxAmount = 29.15m
                        },
                        new
                        {
                            Id = new Guid("cec63725-b0bb-1002-1010-8e3fe6ecc58d"),
                            CategoryId = new Guid("28fa7d43-a972-cc5e-da01-06bd633d5911"),
                            CreatedById = new Guid("1a15ba5a-7e60-1841-098b-e96e718dd423"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1485),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            GrossAmount = 198.93m,
                            ImageUrl = "https://picsum.photos/640/480/?image=778",
                            IsAvailable = false,
                            ModifiedById = new Guid("efd7480f-32dd-0f2f-22d2-721419a14ab9"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1490),
                            Name = "Incredible Granite Chair",
                            NetAmount = 165.78m,
                            SKU = "4341625252266",
                            Tag = "Handmade",
                            TaxAmount = 33.15m
                        },
                        new
                        {
                            Id = new Guid("8a27b0d6-f706-0c8d-2cff-674030b86f0a"),
                            CategoryId = new Guid("28fa7d43-a972-cc5e-da01-06bd633d5911"),
                            CreatedById = new Guid("7c4e8003-f930-6d2e-ff48-8e33efd8ae71"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1571),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 129.66m,
                            ImageUrl = "https://picsum.photos/640/480/?image=628",
                            IsAvailable = false,
                            ModifiedById = new Guid("51dfa4ab-465b-c99d-3d9a-caaf5def97db"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1576),
                            Name = "Fantastic Steel Car",
                            NetAmount = 108.05m,
                            SKU = "3483111891472",
                            Tag = "Handmade",
                            TaxAmount = 21.61m
                        },
                        new
                        {
                            Id = new Guid("e3bcaf1d-3f84-2f96-7f0f-0fb1b304779f"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("c08a90c3-cf01-baa1-df60-e27d765e675a"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1655),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 331.61m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1057",
                            IsAvailable = false,
                            ModifiedById = new Guid("c812010b-067c-e25c-4ead-02aa7c0cb556"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1660),
                            Name = "Intelligent Steel Shirt",
                            NetAmount = 276.34m,
                            SKU = "8860676210668",
                            Tag = "Rustic",
                            TaxAmount = 55.27m
                        },
                        new
                        {
                            Id = new Guid("33bc22ae-72a7-cc53-f73e-d2aa8cd8c2d0"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("293f5001-bbc4-027a-3885-35f5e102c866"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1752),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 730.66m,
                            ImageUrl = "https://picsum.photos/640/480/?image=34",
                            IsAvailable = true,
                            ModifiedById = new Guid("91f66403-32d0-5962-8480-16c33179d040"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1757),
                            Name = "Intelligent Wooden Cheese",
                            NetAmount = 608.88m,
                            SKU = "0198200797681",
                            Tag = "Sleek",
                            TaxAmount = 121.78m
                        },
                        new
                        {
                            Id = new Guid("edcf0031-a5e6-a443-b7d0-bfb4f5ff915b"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("367a0064-e903-3716-3f1c-2595214dc6d2"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1838),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 418.80m,
                            ImageUrl = "https://picsum.photos/640/480/?image=832",
                            IsAvailable = true,
                            ModifiedById = new Guid("50c45ea8-76d7-e37f-ea4e-f0e93b6e475f"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1843),
                            Name = "Small Soft Gloves",
                            NetAmount = 349.0m,
                            SKU = "5524253246596",
                            Tag = "Generic",
                            TaxAmount = 69.80m
                        },
                        new
                        {
                            Id = new Guid("80ed8341-4b96-f8b4-2dfc-d1d5c53c873c"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("80b5a55b-667c-c940-b664-3ccb86de4e61"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1916),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 916.35m,
                            ImageUrl = "https://picsum.photos/640/480/?image=871",
                            IsAvailable = false,
                            ModifiedById = new Guid("161725b1-e923-a695-294f-bb9bdbf4b970"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(1921),
                            Name = "Ergonomic Plastic Towels",
                            NetAmount = 763.62m,
                            SKU = "5657221463982",
                            Tag = "Awesome",
                            TaxAmount = 152.73m
                        },
                        new
                        {
                            Id = new Guid("0f721871-560f-aa2c-a5ed-c2aacbd05930"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("679a0b06-d23c-1fff-6396-40dd6ded6bd0"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2001),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 877.84m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1038",
                            IsAvailable = true,
                            ModifiedById = new Guid("14894b19-373c-c047-9030-9e3608884318"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2006),
                            Name = "Practical Metal Mouse",
                            NetAmount = 731.53m,
                            SKU = "5495718864931",
                            Tag = "Unbranded",
                            TaxAmount = 146.31m
                        },
                        new
                        {
                            Id = new Guid("c4cff344-d6da-340b-c917-da5328c54e46"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("61e04707-fbea-8ae9-ceaa-42f3e6b416f6"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2088),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 358.06m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1027",
                            IsAvailable = false,
                            ModifiedById = new Guid("2ad3d1c2-a0d8-62af-de69-4f3bd125ec89"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2093),
                            Name = "Refined Frozen Table",
                            NetAmount = 298.38m,
                            SKU = "6233211626071",
                            Tag = "Rustic",
                            TaxAmount = 59.68m
                        },
                        new
                        {
                            Id = new Guid("97676d23-837d-ab80-adb8-a9bdb8047439"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("74a3456c-208a-aa94-7fcd-c61b3a3bed94"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2169),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 295.75m,
                            ImageUrl = "https://picsum.photos/640/480/?image=263",
                            IsAvailable = true,
                            ModifiedById = new Guid("04cb9795-1213-9c33-db9d-5c8b4c71dc13"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2173),
                            Name = "Awesome Frozen Gloves",
                            NetAmount = 246.46m,
                            SKU = "7822872812788",
                            Tag = "Licensed",
                            TaxAmount = 49.29m
                        },
                        new
                        {
                            Id = new Guid("12592670-9907-c4ed-085e-0ef1b2405fa7"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("30b3a64e-2ac8-fa57-83de-752ceabf3749"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2247),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 899.26m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1029",
                            IsAvailable = true,
                            ModifiedById = new Guid("b46adabb-8c3b-48e6-7a3e-d05d09be0a25"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2251),
                            Name = "Small Steel Pants",
                            NetAmount = 749.38m,
                            SKU = "6529733835405",
                            Tag = "Incredible",
                            TaxAmount = 149.88m
                        },
                        new
                        {
                            Id = new Guid("bfc26cab-b66a-5989-f9f1-c4d4501b1f43"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("69cbd4c8-e524-fddc-be25-b96487374388"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2325),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 11.85m,
                            ImageUrl = "https://picsum.photos/640/480/?image=191",
                            IsAvailable = false,
                            ModifiedById = new Guid("5e654e32-afb9-3909-e7ec-d66cca54d2a4"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2329),
                            Name = "Unbranded Cotton Mouse",
                            NetAmount = 9.88m,
                            SKU = "8204236225134",
                            Tag = "Handmade",
                            TaxAmount = 1.97m
                        },
                        new
                        {
                            Id = new Guid("ca1989c0-8191-0e38-7033-6a5214a982d8"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("9dc31d52-cf9f-adf5-c43d-c21a13be8db2"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2412),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 834.17m,
                            ImageUrl = "https://picsum.photos/640/480/?image=553",
                            IsAvailable = true,
                            ModifiedById = new Guid("7bfaefd1-2644-edda-79b7-1f9197f2e77b"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2416),
                            Name = "Licensed Plastic Mouse",
                            NetAmount = 695.14m,
                            SKU = "4615527978396",
                            Tag = "Refined",
                            TaxAmount = 139.03m
                        },
                        new
                        {
                            Id = new Guid("422c9406-24d6-b0e7-6416-d15546cc2a63"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("d86cd36e-e70a-20d8-862d-5bbc6debdf71"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2490),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 667.10m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1015",
                            IsAvailable = false,
                            ModifiedById = new Guid("5447ccc1-dc2e-3f08-2e40-305434fe7951"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2495),
                            Name = "Gorgeous Wooden Towels",
                            NetAmount = 555.92m,
                            SKU = "1335253597564",
                            Tag = "Handmade",
                            TaxAmount = 111.18m
                        },
                        new
                        {
                            Id = new Guid("cb9134d5-a92d-b7ca-83ec-88b30aec1fb3"),
                            CategoryId = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("28745dfb-9928-1f22-5f77-02fdb71dd36a"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2569),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 430.05m,
                            ImageUrl = "https://picsum.photos/640/480/?image=725",
                            IsAvailable = true,
                            ModifiedById = new Guid("19faccff-18a5-a3e7-da67-372034f5be3f"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2574),
                            Name = "Small Concrete Soap",
                            NetAmount = 358.38m,
                            SKU = "3455247610630",
                            Tag = "Handcrafted",
                            TaxAmount = 71.67m
                        },
                        new
                        {
                            Id = new Guid("75e20d06-4dd1-61c0-02eb-6ab8c3daf1e0"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("71ae4ad0-06be-ad34-31fc-0d67d0071640"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2661),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 473.24m,
                            ImageUrl = "https://picsum.photos/640/480/?image=349",
                            IsAvailable = true,
                            ModifiedById = new Guid("b71c4d80-8d5a-034e-9ada-108601fde3f2"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2666),
                            Name = "Fantastic Steel Computer",
                            NetAmount = 394.37m,
                            SKU = "3031488860388",
                            Tag = "Awesome",
                            TaxAmount = 78.87m
                        },
                        new
                        {
                            Id = new Guid("fc42863a-d6aa-f6e3-aeac-33181b594abf"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("1ab43a42-dd1d-4825-79c3-414916b0d7c4"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2744),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 600.66m,
                            ImageUrl = "https://picsum.photos/640/480/?image=444",
                            IsAvailable = true,
                            ModifiedById = new Guid("ffd3346e-d605-f55b-4f09-2b8810bb2400"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2749),
                            Name = "Unbranded Metal Towels",
                            NetAmount = 500.55m,
                            SKU = "7375041683431",
                            Tag = "Incredible",
                            TaxAmount = 100.11m
                        },
                        new
                        {
                            Id = new Guid("df6bba4b-cbbe-b114-9d37-bd9f4103db1e"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("931340e8-9f76-540b-7460-b4282eb4a111"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2825),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 979.67m,
                            ImageUrl = "https://picsum.photos/640/480/?image=24",
                            IsAvailable = true,
                            ModifiedById = new Guid("80fa7a3d-0f26-8fc5-8cab-c3c2c4475496"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2829),
                            Name = "Tasty Cotton Cheese",
                            NetAmount = 816.39m,
                            SKU = "8464625408535",
                            Tag = "Rustic",
                            TaxAmount = 163.28m
                        },
                        new
                        {
                            Id = new Guid("7ad9f75b-0784-dbcb-488f-2d0c1e234fc8"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("6ce97972-d14f-a50f-6778-a028da2c18e5"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2903),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 408.26m,
                            ImageUrl = "https://picsum.photos/640/480/?image=428",
                            IsAvailable = true,
                            ModifiedById = new Guid("e7a98e8e-b412-4c13-43cf-66883d51f8c7"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2907),
                            Name = "Gorgeous Soft Car",
                            NetAmount = 340.22m,
                            SKU = "9564130475455",
                            Tag = "Tasty",
                            TaxAmount = 68.04m
                        },
                        new
                        {
                            Id = new Guid("66beb567-299d-6a7f-8767-157fd8f3b909"),
                            CategoryId = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("d4346de5-ff1f-a2de-07e5-9fce4a10f6d3"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2987),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 636.13m,
                            ImageUrl = "https://picsum.photos/640/480/?image=421",
                            IsAvailable = true,
                            ModifiedById = new Guid("6acd4e68-cc64-30db-391f-61ccfc8c8daf"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(2992),
                            Name = "Refined Steel Bike",
                            NetAmount = 530.11m,
                            SKU = "0632333759449",
                            Tag = "Licensed",
                            TaxAmount = 106.02m
                        },
                        new
                        {
                            Id = new Guid("9118a44e-9a04-9e00-12a5-7b57ef86367e"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("f3ad8a1c-9365-6d48-23a6-88ffea5aba75"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3067),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 88.15m,
                            ImageUrl = "https://picsum.photos/640/480/?image=409",
                            IsAvailable = true,
                            ModifiedById = new Guid("6ef98902-4879-2045-5ac9-c576e35f992b"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3072),
                            Name = "Practical Frozen Towels",
                            NetAmount = 73.46m,
                            SKU = "9295038212841",
                            Tag = "Licensed",
                            TaxAmount = 14.69m
                        },
                        new
                        {
                            Id = new Guid("44d304c8-998c-ce9c-d18a-c40c5d15f205"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("c86b0c02-123e-d9ce-e70e-59150d8bdd0a"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3145),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 840.81m,
                            ImageUrl = "https://picsum.photos/640/480/?image=616",
                            IsAvailable = true,
                            ModifiedById = new Guid("f3209e33-7381-fddc-23ec-8b20aa51b4eb"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3150),
                            Name = "Practical Concrete Tuna",
                            NetAmount = 700.68m,
                            SKU = "7119509822242",
                            Tag = "Gorgeous",
                            TaxAmount = 140.13m
                        },
                        new
                        {
                            Id = new Guid("2f8f83ff-a46e-8751-ae2f-95596e555ba3"),
                            CategoryId = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("4f9421e3-bd6a-1587-5ebd-9c2c4573f078"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3228),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 387.02m,
                            ImageUrl = "https://picsum.photos/640/480/?image=761",
                            IsAvailable = false,
                            ModifiedById = new Guid("2ec0f6f5-ca59-f97a-fd2f-87cac824d232"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3233),
                            Name = "Handmade Cotton Chair",
                            NetAmount = 322.52m,
                            SKU = "3015673464155",
                            Tag = "Tasty",
                            TaxAmount = 64.50m
                        },
                        new
                        {
                            Id = new Guid("a619492c-519b-353a-bd4c-39ea6ac7a3aa"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("6b853458-337e-f8de-c8f0-d8ed4d8aacc0"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3308),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 835.97m,
                            ImageUrl = "https://picsum.photos/640/480/?image=815",
                            IsAvailable = false,
                            ModifiedById = new Guid("58379d5a-f1af-1ea8-4f0d-3e2d97c69e5d"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3313),
                            Name = "Awesome Wooden Bike",
                            NetAmount = 696.64m,
                            SKU = "3424811082845",
                            Tag = "Handmade",
                            TaxAmount = 139.33m
                        },
                        new
                        {
                            Id = new Guid("8c66fb4a-1c66-f470-b060-02527a4fbca3"),
                            CategoryId = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("874de2c5-ed3e-138e-fda5-02240b8e1e35"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3385),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 822.23m,
                            ImageUrl = "https://picsum.photos/640/480/?image=869",
                            IsAvailable = true,
                            ModifiedById = new Guid("9453cdd1-5a80-f077-a505-bac0db58fefd"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3390),
                            Name = "Sleek Concrete Chicken",
                            NetAmount = 685.19m,
                            SKU = "5065322970023",
                            Tag = "Refined",
                            TaxAmount = 137.04m
                        },
                        new
                        {
                            Id = new Guid("6a6a2228-e15d-3338-cd37-a5a605f97cb3"),
                            CategoryId = new Guid("28fa7d43-a972-cc5e-da01-06bd633d5911"),
                            CreatedById = new Guid("7c8bf288-27f6-cb2d-b5d7-591b977e0fd6"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3460),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 232.71m,
                            ImageUrl = "https://picsum.photos/640/480/?image=209",
                            IsAvailable = false,
                            ModifiedById = new Guid("6c030151-2b70-64e5-182a-9f1be91b1352"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3464),
                            Name = "Tasty Plastic Table",
                            NetAmount = 193.92m,
                            SKU = "7540773957161",
                            Tag = "Handcrafted",
                            TaxAmount = 38.79m
                        },
                        new
                        {
                            Id = new Guid("0d5c4310-6327-87cc-11e2-9ac306ae28c5"),
                            CategoryId = new Guid("28fa7d43-a972-cc5e-da01-06bd633d5911"),
                            CreatedById = new Guid("fc21e135-7602-76d2-5edc-fb8e50f31ac6"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3543),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 383.46m,
                            ImageUrl = "https://picsum.photos/640/480/?image=213",
                            IsAvailable = true,
                            ModifiedById = new Guid("2c5c5c0f-cc5c-cccd-3878-e4bb1ac2806e"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3548),
                            Name = "Awesome Wooden Tuna",
                            NetAmount = 319.55m,
                            SKU = "3783596312449",
                            Tag = "Ergonomic",
                            TaxAmount = 63.91m
                        },
                        new
                        {
                            Id = new Guid("136968fb-c354-9289-165c-9b5b8d1bc600"),
                            CategoryId = new Guid("970a3739-d92a-3f5b-ba55-4488dea24542"),
                            CreatedById = new Guid("6908922d-bbc3-1e77-8264-fb41c5f4450f"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3618),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 872.39m,
                            ImageUrl = "https://picsum.photos/640/480/?image=510",
                            IsAvailable = false,
                            ModifiedById = new Guid("21771cd6-da89-42df-6907-5a8912efdb22"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3623),
                            Name = "Intelligent Cotton Cheese",
                            NetAmount = 726.99m,
                            SKU = "2855399305353",
                            Tag = "Licensed",
                            TaxAmount = 145.40m
                        },
                        new
                        {
                            Id = new Guid("b35377a4-ffc6-60bc-ee0b-9389d9d0a85a"),
                            CategoryId = new Guid("970a3739-d92a-3f5b-ba55-4488dea24542"),
                            CreatedById = new Guid("8d966403-3037-493e-ef7a-213a3972856a"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3695),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 83.76m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1062",
                            IsAvailable = false,
                            ModifiedById = new Guid("a6cc7e6a-8f46-40e4-d2df-023ffc66ef78"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3700),
                            Name = "Ergonomic Rubber Shirt",
                            NetAmount = 69.8m,
                            SKU = "5598367876895",
                            Tag = "Intelligent",
                            TaxAmount = 13.96m
                        },
                        new
                        {
                            Id = new Guid("7f741402-bb55-2e57-ff4c-888aa916725e"),
                            CategoryId = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("13877c5d-6d59-cb3c-9961-50b886b9d447"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3774),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            GrossAmount = 535.94m,
                            ImageUrl = "https://picsum.photos/640/480/?image=124",
                            IsAvailable = true,
                            ModifiedById = new Guid("b2217495-a89f-2798-1445-39bc3bc0356b"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3778),
                            Name = "Intelligent Wooden Chair",
                            NetAmount = 446.62m,
                            SKU = "5519609582442",
                            Tag = "Practical",
                            TaxAmount = 89.32m
                        },
                        new
                        {
                            Id = new Guid("e3b4bfc0-fe60-3414-7f90-d82ce4046990"),
                            CategoryId = new Guid("970a3739-d92a-3f5b-ba55-4488dea24542"),
                            CreatedById = new Guid("ca4eb027-da8d-c2f6-a5bc-759df344faca"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3860),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 564.06m,
                            ImageUrl = "https://picsum.photos/640/480/?image=285",
                            IsAvailable = true,
                            ModifiedById = new Guid("5df37601-c974-4837-9560-58180ec78699"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3865),
                            Name = "Refined Frozen Pizza",
                            NetAmount = 470.05m,
                            SKU = "5664665197601",
                            Tag = "Tasty",
                            TaxAmount = 94.01m
                        },
                        new
                        {
                            Id = new Guid("785e1b0c-3505-812c-ddb4-dd35dc5f3df3"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("0f972369-930c-8b83-93bf-1e1f1d83019c"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3937),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 172.76m,
                            ImageUrl = "https://picsum.photos/640/480/?image=867",
                            IsAvailable = true,
                            ModifiedById = new Guid("9a318818-17f2-34a2-3a64-ec3d606eac16"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(3942),
                            Name = "Refined Metal Towels",
                            NetAmount = 143.97m,
                            SKU = "9755372282356",
                            Tag = "Refined",
                            TaxAmount = 28.79m
                        },
                        new
                        {
                            Id = new Guid("815201a2-d463-a7a7-452a-2513081bd557"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("83b90817-03b9-321f-5c1e-2d00928a1f51"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4016),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 519.42m,
                            ImageUrl = "https://picsum.photos/640/480/?image=793",
                            IsAvailable = true,
                            ModifiedById = new Guid("4661e858-68d9-8930-5cd1-51a8bf320ef1"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4020),
                            Name = "Intelligent Steel Computer",
                            NetAmount = 432.85m,
                            SKU = "0407486192463",
                            Tag = "Fantastic",
                            TaxAmount = 86.57m
                        },
                        new
                        {
                            Id = new Guid("d7ae7e8e-272f-b1e8-7672-29103b7190ee"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("7488ede6-64c1-43b9-ebe2-b5bc969deb77"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4098),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 963.58m,
                            ImageUrl = "https://picsum.photos/640/480/?image=630",
                            IsAvailable = true,
                            ModifiedById = new Guid("830037ee-61ed-a833-8cee-6badfb346b36"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4102),
                            Name = "Tasty Rubber Table",
                            NetAmount = 802.98m,
                            SKU = "6030968928812",
                            Tag = "Generic",
                            TaxAmount = 160.60m
                        },
                        new
                        {
                            Id = new Guid("ba84000d-e7df-f9d3-0c48-b6767f38c877"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("3f434505-bed6-7582-e637-60d391264913"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4175),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            GrossAmount = 66.45m,
                            ImageUrl = "https://picsum.photos/640/480/?image=734",
                            IsAvailable = true,
                            ModifiedById = new Guid("cd76c568-2ca0-c352-2430-b72235d6f2f3"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4179),
                            Name = "Handcrafted Frozen Sausages",
                            NetAmount = 55.38m,
                            SKU = "6871145860507",
                            Tag = "Sleek",
                            TaxAmount = 11.07m
                        },
                        new
                        {
                            Id = new Guid("f3d8d7fb-1b7f-06a6-6040-0f446d802fa4"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("2ba435de-4f28-5891-a93c-23c8d12491c7"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4249),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 629.99m,
                            ImageUrl = "https://picsum.photos/640/480/?image=372",
                            IsAvailable = false,
                            ModifiedById = new Guid("8a573139-78a9-a85e-f347-1dcfc3641980"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4254),
                            Name = "Fantastic Rubber Bacon",
                            NetAmount = 524.99m,
                            SKU = "7218596906061",
                            Tag = "Practical",
                            TaxAmount = 105.00m
                        },
                        new
                        {
                            Id = new Guid("d766faa4-37fc-32e1-c194-4522a38f8e04"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("98ab5d23-44ab-2e29-1bb0-1511e2207b59"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4325),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 989.55m,
                            ImageUrl = "https://picsum.photos/640/480/?image=284",
                            IsAvailable = true,
                            ModifiedById = new Guid("489357de-96b9-566e-b779-84ea0420544e"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4330),
                            Name = "Unbranded Cotton Chicken",
                            NetAmount = 824.62m,
                            SKU = "7751870336937",
                            Tag = "Sleek",
                            TaxAmount = 164.93m
                        },
                        new
                        {
                            Id = new Guid("ef8d4b46-e154-c032-3e29-fa5cc76aab95"),
                            CategoryId = new Guid("970a3739-d92a-3f5b-ba55-4488dea24542"),
                            CreatedById = new Guid("d93bf991-7733-d981-2234-e728e2d118db"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4408),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 649.61m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1072",
                            IsAvailable = true,
                            ModifiedById = new Guid("eb605207-fbfd-c10b-4a9e-910ec1ee5a65"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4413),
                            Name = "Handcrafted Plastic Salad",
                            NetAmount = 541.34m,
                            SKU = "2553487451806",
                            Tag = "Awesome",
                            TaxAmount = 108.27m
                        },
                        new
                        {
                            Id = new Guid("ee9598c0-8f7a-e594-7218-34da8284d74a"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("8995d326-2190-2f49-ebc6-40c024fda299"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4486),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            GrossAmount = 547.75m,
                            ImageUrl = "https://picsum.photos/640/480/?image=997",
                            IsAvailable = true,
                            ModifiedById = new Guid("72e45ae4-03f2-e28d-33ea-569b98447885"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4490),
                            Name = "Awesome Frozen Car",
                            NetAmount = 456.46m,
                            SKU = "0086365790954",
                            Tag = "Ergonomic",
                            TaxAmount = 91.29m
                        },
                        new
                        {
                            Id = new Guid("45225765-56b2-caa6-ae96-a74ebaba0113"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("e1f8d956-2244-018b-d993-5f29e124fd4e"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4562),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 774.16m,
                            ImageUrl = "https://picsum.photos/640/480/?image=612",
                            IsAvailable = true,
                            ModifiedById = new Guid("cba1e551-06c7-950d-d2d5-a1cf5b659419"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4567),
                            Name = "Handcrafted Steel Hat",
                            NetAmount = 645.13m,
                            SKU = "7874186526233",
                            Tag = "Fantastic",
                            TaxAmount = 129.03m
                        },
                        new
                        {
                            Id = new Guid("cb4f4c36-0e62-816f-bba5-74ff456a8004"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("8a0b503d-ff5f-9ba5-ef9e-55ec17370267"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4646),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 855.17m,
                            ImageUrl = "https://picsum.photos/640/480/?image=1009",
                            IsAvailable = false,
                            ModifiedById = new Guid("148800be-f4d1-379a-ebc0-0f7cf61eb012"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4651),
                            Name = "Incredible Granite Towels",
                            NetAmount = 712.64m,
                            SKU = "7433192007930",
                            Tag = "Tasty",
                            TaxAmount = 142.53m
                        },
                        new
                        {
                            Id = new Guid("b548326c-9ed4-ef9e-29a4-d1ee438592db"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("477375f9-6d50-181c-d67e-68578ad9e9dd"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4723),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            GrossAmount = 459.47m,
                            ImageUrl = "https://picsum.photos/640/480/?image=154",
                            IsAvailable = true,
                            ModifiedById = new Guid("52fa2f6b-5313-ad1e-1a47-7d100ad575fd"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4728),
                            Name = "Tasty Granite Chair",
                            NetAmount = 382.89m,
                            SKU = "1538092553047",
                            Tag = "Handmade",
                            TaxAmount = 76.58m
                        },
                        new
                        {
                            Id = new Guid("56a6c83f-2cc6-f009-0c0e-00096b80e130"),
                            CategoryId = new Guid("970a3739-d92a-3f5b-ba55-4488dea24542"),
                            CreatedById = new Guid("9d6e0f51-3cfb-74e4-c877-d3e32d551753"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4825),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 38.57m,
                            ImageUrl = "https://picsum.photos/640/480/?image=199",
                            IsAvailable = true,
                            ModifiedById = new Guid("e1977261-4102-d007-880f-0921dd4ccac6"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4830),
                            Name = "Unbranded Soft Salad",
                            NetAmount = 32.14m,
                            SKU = "8709105779973",
                            Tag = "Practical",
                            TaxAmount = 6.43m
                        },
                        new
                        {
                            Id = new Guid("08102d00-149d-33ec-c297-7cad0d600dec"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("e3eb4033-fd94-b3d1-b877-624c512a30a5"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4900),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 858.21m,
                            ImageUrl = "https://picsum.photos/640/480/?image=745",
                            IsAvailable = true,
                            ModifiedById = new Guid("f282ddd1-db58-6175-a2cf-219a11a14bc5"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4905),
                            Name = "Gorgeous Granite Pizza",
                            NetAmount = 715.18m,
                            SKU = "1542972212450",
                            Tag = "Ergonomic",
                            TaxAmount = 143.03m
                        },
                        new
                        {
                            Id = new Guid("ca58931b-418a-dbc4-36a2-172b9d978766"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("87bde9c3-957f-8afc-4fae-01ee88333ac5"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4985),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 221.55m,
                            ImageUrl = "https://picsum.photos/640/480/?image=334",
                            IsAvailable = true,
                            ModifiedById = new Guid("3699e81b-a36b-d230-9026-26b938fa1509"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(4989),
                            Name = "Tasty Cotton Soap",
                            NetAmount = 184.62m,
                            SKU = "4818111480347",
                            Tag = "Rustic",
                            TaxAmount = 36.93m
                        },
                        new
                        {
                            Id = new Guid("b820fa50-f7ea-6f58-4252-5599f894568f"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("8a73a64c-9f13-289e-5592-bad32251e6e9"),
                            CreatedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(5060),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 388.01m,
                            ImageUrl = "https://picsum.photos/640/480/?image=332",
                            IsAvailable = true,
                            ModifiedById = new Guid("37090c5f-3483-b134-0516-547b25424742"),
                            ModifiedOn = new DateTime(2026, 2, 14, 10, 7, 1, 24, DateTimeKind.Local).AddTicks(5065),
                            Name = "Gorgeous Granite Hat",
                            NetAmount = 323.34m,
                            SKU = "0905576586159",
                            Tag = "Rustic",
                            TaxAmount = 64.67m
                        });
                });

            modelBuilder.Entity("Shop.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop.Models.OrderDetail", b =>
                {
                    b.HasOne("Shop.Models.OrderHeader", "OrderHeader")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.HasOne("Shop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Models.ShoppingCart", b =>
                {
                    b.HasOne("Shop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shop.Models.OrderHeader", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
