// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Data;

#nullable disable

namespace Shop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214033858_addedOrders")]
    partial class addedOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Shop.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("36427b23-c94b-3806-f0cb-040f87b57cd4"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 541, DateTimeKind.Local).AddTicks(7691),
                            ModifiedById = new Guid("dc8dd8b6-db87-6282-6db9-6d206135fd19"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 548, DateTimeKind.Local).AddTicks(1723),
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("30639e1a-6d4f-f948-e0c8-915ce6d7bbcd"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(2636),
                            ModifiedById = new Guid("30727cea-13ba-1ec2-8b95-a3ad7541c3b9"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(2693),
                            Name = "Movies"
                        },
                        new
                        {
                            Id = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("8e2c363e-0531-dc07-45a4-b9c99a839e04"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3074),
                            ModifiedById = new Guid("908551d8-3324-3a01-caf2-f03296f6e535"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3090),
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = new Guid("970a3739-d92a-3f5b-ba55-4488dea24542"),
                            CreatedById = new Guid("d9554f26-4e7b-350b-f1c4-3f14d4464ebe"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3177),
                            ModifiedById = new Guid("4c613284-6d94-77ad-2a50-6adebcb2eb50"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3188),
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("41ab0485-aef9-a1b9-ddaf-2be42d783fd8"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3226),
                            ModifiedById = new Guid("d6e569ee-2ea7-1728-7520-bfc647dde4e5"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3232),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("85dcab8e-5e9d-dc57-94cb-d8eef259ffca"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3287),
                            ModifiedById = new Guid("4155ef45-9891-b8df-a321-a17a7b276f22"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3302),
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("a917aae2-d41a-ccf5-24e2-7bbcdc616c5b"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3344),
                            ModifiedById = new Guid("a0928bb6-c3cd-96e5-db62-c0ed9adf4f5e"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3352),
                            Name = "Games"
                        },
                        new
                        {
                            Id = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("2fc821e8-e60b-c51e-80cd-b71408314492"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3379),
                            ModifiedById = new Guid("c815c61c-03ef-413d-07dc-68e167ba1f5f"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3386),
                            Name = "Toys"
                        },
                        new
                        {
                            Id = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("edf6bfea-4fa7-e4e5-8628-2e7d3d5dc6ae"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3409),
                            ModifiedById = new Guid("7f59c357-0b86-dbed-344d-382b92af8f21"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3415),
                            Name = "Home"
                        },
                        new
                        {
                            Id = new Guid("28fa7d43-a972-cc5e-da01-06bd633d5911"),
                            CreatedById = new Guid("62b33afd-17b3-d1df-1ab9-5917ba51d699"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3468),
                            ModifiedById = new Guid("e0fa480c-85cc-1ae5-fab2-ab09e71ed010"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 550, DateTimeKind.Local).AddTicks(3474),
                            Name = "Baby"
                        });
                });

            modelBuilder.Entity("Shop.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderHeaderId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId1");

                    b.HasIndex("ProductId1");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Shop.Models.OrderHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderHeader");
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc75941a-81bf-9e2b-280e-b94f4712882a"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("431bb06d-4479-5477-9867-006bd5e9fce8"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 554, DateTimeKind.Local).AddTicks(9132),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            GrossAmount = 799.78m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1950408735",
                            IsAvailable = true,
                            ModifiedById = new Guid("bda03848-bc61-c64d-ce42-a3772ccbb3a0"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 555, DateTimeKind.Local).AddTicks(3595),
                            Name = "Handcrafted Frozen Chicken",
                            NetAmount = 666.48m,
                            SKU = "2674098486848",
                            Tag = "Gorgeous",
                            TaxAmount = 133.30m
                        },
                        new
                        {
                            Id = new Guid("5462b0c9-3674-00a1-28cd-b46047f66f8e"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("cbd37a32-40a0-f579-450e-7964655bc4a3"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(8331),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 229.82m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1887826662",
                            IsAvailable = true,
                            ModifiedById = new Guid("ca15582d-610c-2e59-331c-f875a32077d1"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(8407),
                            Name = "Awesome Wooden Keyboard",
                            NetAmount = 191.52m,
                            SKU = "9918692579845",
                            Tag = "Practical",
                            TaxAmount = 38.30m
                        },
                        new
                        {
                            Id = new Guid("a421d182-8397-0347-5225-96a895e2bd38"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("8b2d8668-9f93-f352-71f6-822b6b93ed88"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9544),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            GrossAmount = 485.71m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1067997728",
                            IsAvailable = true,
                            ModifiedById = new Guid("cc002af0-976a-a70f-4233-19e8ce14a7b7"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9557),
                            Name = "Incredible Granite Mouse",
                            NetAmount = 404.76m,
                            SKU = "8885504797883",
                            Tag = "Unbranded",
                            TaxAmount = 80.95m
                        },
                        new
                        {
                            Id = new Guid("8677d0ce-6049-6985-245c-4eca1c9aeb41"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("1e199ac6-3b4d-6e64-a526-9b5aafc05d3d"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9682),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 616.48m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1092378033",
                            IsAvailable = false,
                            ModifiedById = new Guid("d7031ed5-3b34-b10c-5c15-09d55137fffd"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9688),
                            Name = "Licensed Concrete Sausages",
                            NetAmount = 513.73m,
                            SKU = "2252287247083",
                            Tag = "Refined",
                            TaxAmount = 102.75m
                        },
                        new
                        {
                            Id = new Guid("678e8b0c-38c1-8e31-1c6d-269d87b8783f"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("717b12ec-2b6b-e85a-ec31-5ba5d5404201"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9777),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 364.97m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1378317037",
                            IsAvailable = false,
                            ModifiedById = new Guid("bceac066-e98e-6a01-60dc-ec73fc26a301"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9783),
                            Name = "Sleek Concrete Towels",
                            NetAmount = 304.14m,
                            SKU = "5768134111805",
                            Tag = "Sleek",
                            TaxAmount = 60.83m
                        },
                        new
                        {
                            Id = new Guid("101002b0-8e10-e63f-ecc5-8d5aba151a60"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("0918417e-e98b-716e-8dd4-230f48d7efdd"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9869),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 598.82m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=103633141",
                            IsAvailable = false,
                            ModifiedById = new Guid("220f2f32-72d2-1914-a14a-b9b50283d1a3"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9875),
                            Name = "Sleek Wooden Tuna",
                            NetAmount = 499.02m,
                            SKU = "2525226719874",
                            Tag = "Intelligent",
                            TaxAmount = 99.80m
                        },
                        new
                        {
                            Id = new Guid("ff2c0c8d-4067-b830-6f0a-03804e7c30f9"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("48ff6d2e-338e-d8ef-ae71-aba4df515b46"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9967),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            GrossAmount = 481.53m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1482089870",
                            IsAvailable = true,
                            ModifiedById = new Guid("9a3dc99d-afca-ef5d-97db-2f7839eae121"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 564, DateTimeKind.Local).AddTicks(9972),
                            Name = "Incredible Wooden Computer",
                            NetAmount = 401.28m,
                            SKU = "1891475108792",
                            Tag = "Handmade",
                            TaxAmount = 80.25m
                        },
                        new
                        {
                            Id = new Guid("0f0f7f2f-b3b1-7704-9fc3-908ac001cfa1"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("e260dfba-767d-675e-5a0b-0112c87c065c"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(60),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            GrossAmount = 404.84m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=53376622",
                            IsAvailable = true,
                            ModifiedById = new Guid("02ad4ee2-7caa-b50c-56a5-b48d650acbd8"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(65),
                            Name = "Generic Metal Tuna",
                            NetAmount = 337.37m,
                            SKU = "2106693181151",
                            Tag = "Tasty",
                            TaxAmount = 67.47m
                        },
                        new
                        {
                            Id = new Guid("aad23ef7-d88c-d0c2-0150-3f29c4bb7a02"),
                            CategoryId = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("f5358538-02e1-66c8-0364-f691d0326259"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(153),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 197.83m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1158922983",
                            IsAvailable = true,
                            ModifiedById = new Guid("c3168084-7931-40d0-f650-a66466882df3"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(159),
                            Name = "Small Steel Cheese",
                            NetAmount = 164.86m,
                            SKU = "9768074247318",
                            Tag = "Generic",
                            TaxAmount = 32.97m
                        },
                        new
                        {
                            Id = new Guid("f5b4bfd0-91ff-645b-007a-3603e916373f"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("2195251c-c64d-a8d2-5ec4-50d7767fe3ea"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(252),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 997.46m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=118393535",
                            IsAvailable = true,
                            ModifiedById = new Guid("3be9f04e-476e-595f-9911-6a2cf2de48e9"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(257),
                            Name = "Fantastic Plastic Table",
                            NetAmount = 831.22m,
                            SKU = "6597414527567",
                            Tag = "Sleek",
                            TaxAmount = 166.24m
                        },
                        new
                        {
                            Id = new Guid("3cc5d5d1-3c87-a55b-b580-7c6640c9b664"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("de86cb3c-614e-25b1-1716-23e995a6294f"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(343),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 802.24m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=457254391",
                            IsAvailable = true,
                            ModifiedById = new Guid("f4db9bbb-70b9-2dfb-ae47-5616bddb4324"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(349),
                            Name = "Fantastic Rubber Pants",
                            NetAmount = 668.53m,
                            SKU = "9889795667183",
                            Tag = "Refined",
                            TaxAmount = 133.71m
                        },
                        new
                        {
                            Id = new Guid("59d0cbaa-0630-9a0b-673c-d2ff1f639640"),
                            CategoryId = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("6bed6ddd-19d0-894b-143c-3747c090309e"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(434),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 852.43m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1777510507",
                            IsAvailable = true,
                            ModifiedById = new Guid("43880836-1818-a71e-6489-38e99e1952ac"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(440),
                            Name = "Handcrafted Cotton Salad",
                            NetAmount = 710.36m,
                            SKU = "3986381770015",
                            Tag = "Tasty",
                            TaxAmount = 142.07m
                        },
                        new
                        {
                            Id = new Guid("464ec528-4707-61e0-eafb-e98aceaa42f3"),
                            CategoryId = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("f616b4e6-d1c2-2ad3-d8a0-af62de694f3b"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(527),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            GrossAmount = 725.26m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=2004088384",
                            IsAvailable = true,
                            ModifiedById = new Guid("89ec25d1-71ee-aa7a-b11f-5c490a44f52f"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(533),
                            Name = "Generic Steel Fish",
                            NetAmount = 604.38m,
                            SKU = "9329176808830",
                            Tag = "Tasty",
                            TaxAmount = 120.88m
                        },
                        new
                        {
                            Id = new Guid("6c397404-a345-8a74-2094-aa7fcdc61b3a"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("9594ed3b-cb97-1304-1233-9cdb9d5c8b4c"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(617),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 316.02m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=773463709",
                            IsAvailable = true,
                            ModifiedById = new Guid("da13dc71-94da-ed9e-e267-02d9bc17b0bd"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(622),
                            Name = "Handmade Fresh Bike",
                            NetAmount = 263.35m,
                            SKU = "2017205211306",
                            Tag = "Generic",
                            TaxAmount = 52.67m
                        },
                        new
                        {
                            Id = new Guid("a64ea75f-30b3-2ac8-57fa-83de752ceabf"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("dabb4937-b46a-8c3b-e648-7a3ed05d09be"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(705),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 706.52m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1308798460",
                            IsAvailable = true,
                            ModifiedById = new Guid("cb11250a-6e7c-f074-7045-cf5e8e2823c0"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(711),
                            Name = "Ergonomic Frozen Salad",
                            NetAmount = 588.77m,
                            SKU = "4231303663739",
                            Tag = "Awesome",
                            TaxAmount = 117.75m
                        },
                        new
                        {
                            Id = new Guid("cbd4c843-2469-dce5-fdbe-25b964873743"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("654e3288-b95e-09af-39e7-ecd66cca54d2"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(794),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 487.67m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=485955173",
                            IsAvailable = true,
                            ModifiedById = new Guid("5e05baa4-6bf0-b16f-c68f-c40145fc25d1"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(800),
                            Name = "Intelligent Steel Table",
                            NetAmount = 406.39m,
                            SKU = "8781566193918",
                            Tag = "Generic",
                            TaxAmount = 81.28m
                        },
                        new
                        {
                            Id = new Guid("9dc31d52-cf9f-adf5-c43d-c21a13be8db2"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("7bfaefd1-2644-edda-79b7-1f9197f2e77b"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(889),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 527.49m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=2011485800",
                            IsAvailable = true,
                            ModifiedById = new Guid("1f5be94e-64de-f016-946b-0553bf1dfab1"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(895),
                            Name = "Refined Fresh Pants",
                            NetAmount = 439.58m,
                            SKU = "8883591493282",
                            Tag = "Fantastic",
                            TaxAmount = 87.91m
                        },
                        new
                        {
                            Id = new Guid("0ad86cd3-d8e7-8620-2d5b-bc6debdf71c1"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("2e5447cc-08dc-2e3f-4030-5434fe7951d0"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(980),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 127.60m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=194593957",
                            IsAvailable = true,
                            ModifiedById = new Guid("14e4374e-a44d-bb1f-0cbc-a8c82b427837"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(985),
                            Name = "Practical Fresh Cheese",
                            NetAmount = 106.33m,
                            SKU = "2677119148121",
                            Tag = "Ergonomic",
                            TaxAmount = 21.27m
                        },
                        new
                        {
                            Id = new Guid("99282874-1f22-775f-02fd-b71dd36affcc"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("18a519fa-a3e7-67da-3720-34f5be3f23c5"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1068),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 908.94m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=567325725",
                            IsAvailable = true,
                            ModifiedById = new Guid("511f033c-3c5b-7112-6bb6-a7cc0066181e"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1074),
                            Name = "Intelligent Metal Hat",
                            NetAmount = 757.45m,
                            SKU = "3818088806493",
                            Tag = "Handmade",
                            TaxAmount = 151.49m
                        },
                        new
                        {
                            Id = new Guid("3406be71-31ad-0dfc-67d0-071640804d1c"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("4e8d5ab7-9a03-10da-8601-fde3f20e8648"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1162),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 673.67m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=966953299",
                            IsAvailable = false,
                            ModifiedById = new Guid("33cc06d3-d9ff-4434-d440-5990fad52938"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1168),
                            Name = "Awesome Soft Towels",
                            NetAmount = 561.39m,
                            SKU = "1834694018763",
                            Tag = "Ergonomic",
                            TaxAmount = 112.28m
                        },
                        new
                        {
                            Id = new Guid("4825dd1d-c379-4941-16b0-d7c46e34d3ff"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("f55bd605-094f-882b-10bb-2400453a92ee"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1250),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 841.11m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=626823057",
                            IsAvailable = true,
                            ModifiedById = new Guid("5da05a84-fa60-e682-959a-e0fdd46faae7"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1256),
                            Name = "Gorgeous Steel Shirt",
                            NetAmount = 700.92m,
                            SKU = "9145270781165",
                            Tag = "Handmade",
                            TaxAmount = 140.19m
                        },
                        new
                        {
                            Id = new Guid("74540b9f-b460-2e28-b4a1-113d7afa8026"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("8c8fc50f-c3ab-c4c2-4754-9604dfeb2e97"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1338),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 706.76m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=792656923",
                            IsAvailable = true,
                            ModifiedById = new Guid("afab0e53-6a17-165e-eb83-e995ac62c608"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1344),
                            Name = "Rustic Cotton Ball",
                            NetAmount = 588.97m,
                            SKU = "3134975010607",
                            Tag = "Gorgeous",
                            TaxAmount = 117.79m
                        },
                        new
                        {
                            Id = new Guid("7867a50f-28a0-2cda-18e5-8e8ea9e712b4"),
                            CategoryId = new Guid("970a3739-d92a-3f5b-ba55-4488dea24542"),
                            CreatedById = new Guid("cf434c13-8866-513d-f8c7-342023327859"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1432),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 471.38m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1280387826",
                            IsAvailable = true,
                            ModifiedById = new Guid("34e88ab9-0b12-a366-011c-77477e8f7967"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1438),
                            Name = "Licensed Cotton Pants",
                            NetAmount = 392.82m,
                            SKU = "2555079587634",
                            Tag = "Handcrafted",
                            TaxAmount = 78.56m
                        },
                        new
                        {
                            Id = new Guid("9fe507a2-4ace-f610-d368-4ecd6a64ccdb"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("611f3930-fccc-8d8c-af47-1392da49bb5a"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1520),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 857.60m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1279373508",
                            IsAvailable = true,
                            ModifiedById = new Guid("5e1cd767-89b7-20b1-7671-42168a264ea4"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1526),
                            Name = "Generic Frozen Shirt",
                            NetAmount = 714.67m,
                            SKU = "6030439929409",
                            Tag = "Gorgeous",
                            TaxAmount = 142.93m
                        },
                        new
                        {
                            Id = new Guid("ff88a623-5aea-75ba-0289-f96e79484520"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("76c5c95a-5fe3-2b99-e9f7-55b76996c0bb"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1608),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            GrossAmount = 157.41m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=52501833",
                            IsAvailable = true,
                            ModifiedById = new Guid("5e6eaa5c-0012-b7b3-eb05-55668dc804d3"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1614),
                            Name = "Tasty Soft Tuna",
                            NetAmount = 131.18m,
                            SKU = "8333123791411",
                            Tag = "Unbranded",
                            TaxAmount = 26.23m
                        },
                        new
                        {
                            Id = new Guid("0d15590e-dd8b-330a-9e20-f38173dcfd23"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("aa208bec-b451-c0eb-b2e8-f9e99e4eb636"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1702),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 141.94m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=940947928",
                            IsAvailable = true,
                            ModifiedById = new Guid("407e5df9-c087-ac45-b9d9-bff4ff838f2f"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1708),
                            Name = "Handcrafted Fresh Table",
                            NetAmount = 118.28m,
                            SKU = "0381521618395",
                            Tag = "Gorgeous",
                            TaxAmount = 23.66m
                        },
                        new
                        {
                            Id = new Guid("73452c9c-78f0-f6f5-c02e-59ca7af9fd2f"),
                            CategoryId = new Guid("970a3739-d92a-3f5b-ba55-4488dea24542"),
                            CreatedById = new Guid("24c8ca87-32d2-a264-c998-44708a42fb7a"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1790),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 861.36m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1090943934",
                            IsAvailable = false,
                            ModifiedById = new Guid("2508b1d1-3a41-1c3f-6377-942c4919a69b"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1796),
                            Name = "Generic Soft Table",
                            NetAmount = 717.8m,
                            SKU = "5359350618478",
                            Tag = "Refined",
                            TaxAmount = 143.56m
                        },
                        new
                        {
                            Id = new Guid("ac8a4ded-5ac0-379d-58af-f1a81e4f0d3e"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("9ec6972d-9e5d-e790-e7de-0c16f96b21de"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1879),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 435.00m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=791306505",
                            IsAvailable = true,
                            ModifiedById = new Guid("e84c79aa-9f32-9078-cc8f-4afb668c661c"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1885),
                            Name = "Licensed Soft Salad",
                            NetAmount = 362.5m,
                            SKU = "8177495128105",
                            Tag = "Tasty",
                            TaxAmount = 72.50m
                        },
                        new
                        {
                            Id = new Guid("351e8e0b-cdd1-9453-805a-77f0a505bac0"),
                            CategoryId = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("fdfe58db-8f2b-96da-4345-515d6d538ec1"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1973),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 758.35m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1373395094",
                            IsAvailable = true,
                            ModifiedById = new Guid("22e94c19-cc41-ac81-fb28-226a6a5de138"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(1979),
                            Name = "Small Metal Soap",
                            NetAmount = 631.96m,
                            SKU = "3652243673540",
                            Tag = "Refined",
                            TaxAmount = 126.39m
                        },
                        new
                        {
                            Id = new Guid("51d60f7e-0301-706c-2be5-64182a9f1be9"),
                            CategoryId = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("6c52131b-b96f-f5d9-3005-00f59eb48687"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2061),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 450.73m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=134655684",
                            IsAvailable = true,
                            ModifiedById = new Guid("284f9b1d-54ce-f503-1043-5c0d2763cc87"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2066),
                            Name = "Generic Plastic Chicken",
                            NetAmount = 375.61m,
                            SKU = "6980052286505",
                            Tag = "Fantastic",
                            TaxAmount = 75.12m
                        },
                        new
                        {
                            Id = new Guid("5c0fc61a-2c5c-cc5c-cdcc-3878e4bb1ac2"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("8a736e80-edf2-0633-f399-70e5ae4b683d"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2155),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            GrossAmount = 430.88m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=119580478",
                            IsAvailable = false,
                            ModifiedById = new Guid("d4c71e37-aab3-fb51-6869-1354c3899216"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2161),
                            Name = "Awesome Frozen Soap",
                            NetAmount = 359.07m,
                            SKU = "1127639543216",
                            Tag = "Generic",
                            TaxAmount = 71.81m
                        },
                        new
                        {
                            Id = new Guid("771cd60f-8921-dfda-4269-075a8912efdb"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("991d7122-aa42-8e40-40f0-4a90f0c848cc"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2249),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 490.80m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1458362045",
                            IsAvailable = true,
                            ModifiedById = new Guid("848c1621-a370-77a4-53b3-c6ffbc60ee0b"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2255),
                            Name = "Fantastic Plastic Keyboard",
                            NetAmount = 409.0m,
                            SKU = "2484228496728",
                            Tag = "Generic",
                            TaxAmount = 81.80m
                        },
                        new
                        {
                            Id = new Guid("a6cc7e6a-8f46-40e4-d2df-023ffc66ef78"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("2813c624-e2ee-736b-3809-c34bde81267b"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2336),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 770.07m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=713057751",
                            IsAvailable = true,
                            ModifiedById = new Guid("5a1e2886-0203-7414-7f55-bb572eff4c88"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2342),
                            Name = "Tasty Wooden Shirt",
                            NetAmount = 641.72m,
                            SKU = "8801304553085",
                            Tag = "Licensed",
                            TaxAmount = 128.35m
                        },
                        new
                        {
                            Id = new Guid("9fb22174-98a8-1427-4539-bc3bc0356bb4"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("97ac291d-a947-d894-a8e6-f36b9ea74678"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2423),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            GrossAmount = 377.62m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1795832910",
                            IsAvailable = false,
                            ModifiedById = new Guid("f434f540-bfc0-e3b4-60fe-14347f90d82c"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2429),
                            Name = "Refined Soft Soap",
                            NetAmount = 314.68m,
                            SKU = "1620810040097",
                            Tag = "Ergonomic",
                            TaxAmount = 62.94m
                        },
                        new
                        {
                            Id = new Guid("c9745df3-4837-6095-5818-0ec786993db5"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("69a79050-e667-f1c9-3ea3-8876413b950d"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2510),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            GrossAmount = 5.95m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1187165582",
                            IsAvailable = true,
                            ModifiedById = new Guid("0c116d2b-5e1b-0578-352c-81ddb4dd35dc"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2515),
                            Name = "Licensed Concrete Hat",
                            NetAmount = 4.96m,
                            SKU = "9344773157938",
                            Tag = "Fantastic",
                            TaxAmount = 0.99m
                        },
                        new
                        {
                            Id = new Guid("a217f29a-3a34-ec64-3d60-6eac1603472b"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("045e93e9-9778-e5d3-4516-0d6459b3411d"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2604),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 16.21m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1337949124",
                            IsAvailable = true,
                            ModifiedById = new Guid("01a22e53-8152-d463-a7a7-452a2513081b"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2610),
                            Name = "Fantastic Soft Car",
                            NetAmount = 13.51m,
                            SKU = "4883025113360",
                            Tag = "Practical",
                            TaxAmount = 2.70m
                        },
                        new
                        {
                            Id = new Guid("893068d9-d15c-a851-bf32-0ef18f029c39"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("9f74d063-1fe1-4425-a7a7-14bb0bd4ba1f"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2693),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 751.27m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1799125237",
                            IsAvailable = true,
                            ModifiedById = new Guid("ae7e8eba-2fd7-e827-b176-7229103b7190"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2699),
                            Name = "Rustic Wooden Soap",
                            NetAmount = 626.06m,
                            SKU = "6098757624000",
                            Tag = "Generic",
                            TaxAmount = 125.21m
                        },
                        new
                        {
                            Id = new Guid("8ca83361-6bee-fbad-346b-3683cd25e632"),
                            CategoryId = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("c429f8ab-eb6a-714d-2b1b-d986b1210370"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2780),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 541.24m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=485236341",
                            IsAvailable = true,
                            ModifiedById = new Guid("ba84000d-e7df-f9d3-0c48-b6767f38c877"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2786),
                            Name = "Small Frozen Table",
                            NetAmount = 451.03m,
                            SKU = "8599320515094",
                            Tag = "Generic",
                            TaxAmount = 90.21m
                        },
                        new
                        {
                            Id = new Guid("3024c352-22b7-d635-f2f3-5261816bddc3"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("0f7d4e9a-a8d3-0087-68e6-fea30eb9c1fb"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2876),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 417.16m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1400381980",
                            IsAvailable = true,
                            ModifiedById = new Guid("7ff3d8d7-a61b-6006-400f-446d802fa4de"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2882),
                            Name = "Handcrafted Cotton Pants",
                            NetAmount = 347.63m,
                            SKU = "7707667227674",
                            Tag = "Ergonomic",
                            TaxAmount = 69.53m
                        },
                        new
                        {
                            Id = new Guid("1d47f3a8-c3cf-1964-8038-421f6d6a8e98"),
                            CategoryId = new Guid("0731b960-5860-df79-d1ab-44d853c2abb3"),
                            CreatedById = new Guid("497f45ab-f743-35de-3bae-480a3b29a4fa"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2964),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 9.06m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1201939499",
                            IsAvailable = true,
                            ModifiedById = new Guid("37fcd766-32e1-94c1-4522-a38f8e04235d"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(2969),
                            Name = "Intelligent Fresh Salad",
                            NetAmount = 7.55m,
                            SKU = "9811685067445",
                            Tag = "Intelligent",
                            TaxAmount = 1.51m
                        },
                        new
                        {
                            Id = new Guid("ea8479b7-2004-4e54-a636-8aea5fa27d5f"),
                            CategoryId = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("4bbc38d0-cf21-a150-18eb-444cfc464b8d"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3051),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            GrossAmount = 8.09m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1324516783",
                            IsAvailable = true,
                            ModifiedById = new Guid("32e154ef-3ec0-fa29-5cc7-6aab9591f93b"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3056),
                            Name = "Tasty Fresh Bike",
                            NetAmount = 6.74m,
                            SKU = "5989388987507",
                            Tag = "Small",
                            TaxAmount = 1.35m
                        },
                        new
                        {
                            Id = new Guid("c10e919e-5aee-a465-0b87-f20872c8cfc9"),
                            CategoryId = new Guid("1e1d4dcb-25d7-88b8-173b-ef553bbe2bf4"),
                            CreatedById = new Guid("fa1fccb3-de09-106c-1f55-750ac09895ee"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3149),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            GrossAmount = 819.77m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=580979654",
                            IsAvailable = false,
                            ModifiedById = new Guid("e5948f7a-1872-da34-8284-d74a26d39589"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3155),
                            Name = "Licensed Concrete Ball",
                            NetAmount = 683.14m,
                            SKU = "0685989064900",
                            Tag = "Sleek",
                            TaxAmount = 136.63m
                        },
                        new
                        {
                            Id = new Guid("44989b56-8578-2206-ea4c-c0eb799f4f66"),
                            CategoryId = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("d34fb302-74c0-9a76-f627-a065572245b2"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3236),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            GrossAmount = 907.58m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=731101980",
                            IsAvailable = false,
                            ModifiedById = new Guid("aecaa656-a796-ba4e-ba01-1356d9f8e144"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3242),
                            Name = "Licensed Soft Computer",
                            NetAmount = 756.32m,
                            SKU = "8855959005529",
                            Tag = "Small",
                            TaxAmount = 151.26m
                        },
                        new
                        {
                            Id = new Guid("94655bcf-be19-2061-c0fd-455b42cb216b"),
                            CategoryId = new Guid("c1c28515-b9f4-4602-e42e-0c21a90061bf"),
                            CreatedById = new Guid("e87df61e-9889-fd59-d518-364c4fcb620e"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3323),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            GrossAmount = 280.93m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=14341253",
                            IsAvailable = false,
                            ModifiedById = new Guid("a5bb816f-ff74-6a45-8004-3d500b8a5fff"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3329),
                            Name = "Handcrafted Wooden Chicken",
                            NetAmount = 234.11m,
                            SKU = "9679064790410",
                            Tag = "Unbranded",
                            TaxAmount = 46.82m
                        },
                        new
                        {
                            Id = new Guid("12b01ef6-8567-085b-f24b-b937a6b4dcc4"),
                            CategoryId = new Guid("87beb2ae-eb2f-7ae1-b7d7-ab9177bb339d"),
                            CreatedById = new Guid("846982b8-0da2-4440-e26c-3248b5d49e9e"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3417),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            GrossAmount = 820.49m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1513941903",
                            IsAvailable = true,
                            ModifiedById = new Guid("d1a429ef-43ee-9285-dbf9-757347506d1c"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3422),
                            Name = "Unbranded Fresh Shoes",
                            NetAmount = 683.74m,
                            SKU = "8493748576340",
                            Tag = "Ergonomic",
                            TaxAmount = 136.75m
                        },
                        new
                        {
                            Id = new Guid("d6fd75d5-a9a9-cd98-fd91-ff152fde5535"),
                            CategoryId = new Guid("3fad36d7-b10f-b541-05b3-adef06fe5c66"),
                            CreatedById = new Guid("ba506447-82f3-8a13-3fc8-a656c62c09f0"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3503),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 5.78m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=382970135",
                            IsAvailable = true,
                            ModifiedById = new Guid("09000e0c-806b-30e1-510f-6e9dfb3ce474"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3509),
                            Name = "Unbranded Metal Cheese",
                            NetAmount = 4.82m,
                            SKU = "2360778135518",
                            Tag = "Generic",
                            TaxAmount = 0.96m
                        },
                        new
                        {
                            Id = new Guid("1f82c6ca-e368-7613-8e03-e4318d4e5825"),
                            CategoryId = new Guid("587c98c7-4979-c38b-65e2-7ddcbc026f3e"),
                            CreatedById = new Guid("adf7b7c2-f8a7-00e9-2d10-089d14ec33c2"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3592),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            GrossAmount = 240.32m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1281508560",
                            IsAvailable = true,
                            ModifiedById = new Guid("0dad7c97-0d60-33ec-40eb-e394fdd1b3b8"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3597),
                            Name = "Handcrafted Soft Ball",
                            NetAmount = 200.27m,
                            SKU = "9142517081804",
                            Tag = "Ergonomic",
                            TaxAmount = 40.05m
                        },
                        new
                        {
                            Id = new Guid("c3cab5c5-bb6d-5514-025c-5c5026b2a0e1"),
                            CategoryId = new Guid("90a76fef-1a5c-2beb-d4a6-669a466a7406"),
                            CreatedById = new Guid("dcd76698-dd30-931b-58ca-8a41c4db36a2"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3689),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            GrossAmount = 785.29m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=5857132",
                            IsAvailable = true,
                            ModifiedById = new Guid("979d2b17-6687-e9c3-bd87-7f95fc8a4fae"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3695),
                            Name = "Handmade Wooden Towels",
                            NetAmount = 654.41m,
                            SKU = "4206076809684",
                            Tag = "Ergonomic",
                            TaxAmount = 130.88m
                        },
                        new
                        {
                            Id = new Guid("eda33259-a81e-865d-97cd-7adb40d65303"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("b5105268-50fd-20fa-b8ea-f7586f425255"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3776),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            GrossAmount = 9.50m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=1422449321",
                            IsAvailable = true,
                            ModifiedById = new Guid("5694f899-4c8f-73a6-8a13-9f9e285592ba"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3782),
                            Name = "Awesome Metal Towels",
                            NetAmount = 7.92m,
                            SKU = "6892084740194",
                            Tag = "Gorgeous",
                            TaxAmount = 1.58m
                        },
                        new
                        {
                            Id = new Guid("9cac1b73-e92b-5bb1-f763-573c854cf16b"),
                            CategoryId = new Guid("9a964660-42e9-3da8-c9e1-2b28a65f0c73"),
                            CreatedById = new Guid("8bec396b-0c1e-7117-c284-fc4b2303134a"),
                            CreatedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3864),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            GrossAmount = 940.76m,
                            ImageUrl = "https://loremflickr.com/640/480/computer/any?lock=973522437",
                            IsAvailable = false,
                            ModifiedById = new Guid("36afd678-4c3a-2234-57dc-8bd1dc7480ca"),
                            ModifiedOn = new DateTime(2026, 2, 14, 4, 38, 55, 565, DateTimeKind.Local).AddTicks(3870),
                            Name = "Small Metal Shirt",
                            NetAmount = 783.97m,
                            SKU = "3629153508415",
                            Tag = "Incredible",
                            TaxAmount = 156.79m
                        });
                });

            modelBuilder.Entity("Shop.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Shop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shop.Models.OrderDetail", b =>
                {
                    b.HasOne("Shop.Models.OrderHeader", "OrderHeader")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderHeaderId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Models.Product", b =>
                {
                    b.HasOne("Shop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Models.ShoppingCart", b =>
                {
                    b.HasOne("Shop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shop.Models.OrderHeader", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
